### PR TITLE
Add documentation for applications of Casanovo

### PR DESCRIPTION
**Pull request by melihyilmaz**
Added a new readthedocs page with links to papers using Casanovo, with one sentence descriptions for each.

Addresses issue #415

### CODE REVIEW

**Review by wsnoble — APPROVED** [review]
Looks good. Let's see if Wout also wants to review it before merging.

**Comment by bittremieux** [comment]
Should we include some more information about the applications (authors, year, journal) for better referencing?

**Comment by bittremieux** [comment]
Maybe also add a "Last updated on XXX." statement at the bottom, because you run the risk that this quickly becomes outdated.

Additionally, something like "Contact us with your applications of Casanovo to feature your research here", and some instructions on how they should do that through GitHub maybe?

**Comment by wsnoble** [comment]
I like all three of Wout's suggestions.  Melih, will you please make these changes?

**Comment by melihyilmaz** [comment]
Thanks Wout, I made the changes.

**Review by bittremieux — APPROVED** [review]

**Pull request merged**
