### PR TITLE
Replace list comprehension with slicing

### PR DESCRIPTION
**Pull request by seantur**
Thanks for the great work on Casanovo!

I was doing some profiling and noticed that this list comprehension was taking quite a bit of time, at least for my workloads. Replacing it with slicing offers a pretty significant speed up. I'm not totally sure if the dtype needs to be `float64` - I just made the type match the implementation of the v3.2.0 release.

I'm happy to make any changes.

### CODE REVIEW

**Review by bittremieux — APPROVED** [review]
Hi Sean, this looks great. Thank you for the contribution.

Moving the full array from the GPU to CPU in a single operation, rather than individual elements during the list comprehension, is indeed considerably more efficient.

**Review by bittremieux — CHANGES_REQUESTED** [review]
There does still seem to be an issue with the unit tests though. Do you mind checking what's going on there and making sure that everything works?

**Comment by seantur** [comment]
Hi Wout,

Thanks for the feedback. I was in fact missing a `len`. The unit tests also pointed out that if the tensor requires grad, that you need to `detach` before calling numpy.

The unit tests are now passing locally for me.

Happy to make any more changes if needed.

**Review by bittremieux — COMMENTED** [review]
Looks good. I'm going to hold off on merging the PR for the moment though because I've been doing some refactoring of the prediction caching functionality, which will cause some merge conflicts with these changes. I might directly incorporate this in my PR instead.

**Pull request closed without merging**
