### PR TITLE
devices as a special parameter to check types for

### PR DESCRIPTION
**Pull request by gdewael**
Added `"devices"` as a special parameter to check the type against in `validate_param()`.

`isinstance()` allows to check the type using either a type or a tuple of types, allowing more flexibility.

In principle, every parameter could be checked using `isinstance`, although the logic is a bit different. The code for the other parameters now checks if said variable _can_ be casted to the desired type, whereas `isinstance` solely checks if they're already the correct type. (For example, specifying `devices: "2"` in the `config.yaml` file will now raise an error, whereas this was not the case previously)

### CODE REVIEW

**Comment by bittremieux** [comment]
A disadvantage of this change is that if `devices` is a list, the elements of this list are not type checked. So if a user specifies `devices: ["foo", "bar"]` this will pass the config validation but result in an error further down in the code.

Maybe an alternative solution could be to use the built-in Python type hints with a library like [typeguard](https://github.com/agronholm/typeguard) to validate arbitrarily complex values?

@wfondrie what do you think?

**Comment by bittremieux** [comment]
Alternatively, fine-grained GPU control can always be performed outside of Casanovo by setting [`CUDA_VISIBLE_DEVICES`](https://github.com/Noble-Lab/casanovo/issues/281#issuecomment-1910564013).

**Comment by gdewael** [comment]
An alternative requiring fewer code changes, but still allowing more flexibility in the config is to change the required datatype of `devices` as `str`. In PyTorch Lightning, this still allows flexible choice of GPUs (e.g. `"2"` select whatever two gpus, while `"2,3"` selects those specific gpus, and `"2,"` selects only the second gpu specifically).

But honestly, setting `CUDA_VISIBLE_DEVICES` is also sufficient given some documentation.

**Comment by bittremieux** [comment]
Superseded by 6ee6351.

**Comment by bittremieux** [comment]
Thanks for the feedback and contributions @gdewael.

**Pull request closed without merging**
